# Generated by Django 5.0.4 on 2024-12-06 05:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the item",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time when the item was created modified",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time when the item was last modified",
                        verbose_name="Date modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the country",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug based on the country name",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "iso_code_numeric",
                    models.CharField(
                        help_text="ISO code numeric of the country",
                        max_length=3,
                        unique=True,
                        verbose_name="ISO code numeric",
                    ),
                ),
                (
                    "iso_code_alpha2",
                    models.CharField(
                        help_text="ISO code alpha-2 of the country",
                        max_length=2,
                        unique=True,
                        verbose_name="ISO code alpha 2",
                    ),
                ),
                (
                    "iso_code_alpha3",
                    models.CharField(
                        help_text="ISO code alpha-3 of the country",
                        max_length=3,
                        unique=True,
                        verbose_name="ISO code alpha 3",
                    ),
                ),
                (
                    "phone_code",
                    models.PositiveIntegerField(
                        help_text="Phone code of the country (e.g., 1, 44, etc...)",
                        verbose_name="Phone code",
                    ),
                ),
                (
                    "flag",
                    models.ImageField(
                        blank=True,
                        help_text="Flag of the country",
                        null=True,
                        upload_to="flags",
                        verbose_name="Flag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SubnationalRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the item",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time when the item was created modified",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time when the item was last modified",
                        verbose_name="Date modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the subnational region (aka state/province/region)",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="The slug based on the country name",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Country of the subnational region",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subnational_regions",
                        to="core.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subnational Region",
                "verbose_name_plural": "Subnational Regions",
                "ordering": ("name",),
            },
        ),
    ]
