# Generated by Django 5.0.4 on 2024-12-06 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0001_initial"),
        ("supplier", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the item",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time when the item was created modified",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time when the item was last modified",
                        verbose_name="Date modified",
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        blank=True,
                        help_text="Server date and time when the item was deleted",
                        null=True,
                        verbose_name="Date deleted",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the item has been deleted or not",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the inquirer",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the inquirer",
                        max_length=255,
                        verbose_name="Email",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization of the inquirer",
                        max_length=255,
                        null=True,
                        verbose_name="Organization",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Position of the person making the inquiry",
                        max_length=255,
                        null=True,
                        verbose_name="Position",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Message of the person making the inquiry",
                        max_length=6000,
                        verbose_name="Content",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes of the inquiry",
                        max_length=6000,
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("error", "Error"),
                            ("other", "Other"),
                        ],
                        default="processing",
                        help_text="Status of the inquiry",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="unknown",
                        help_text="Importance of the inquiry",
                        max_length=20,
                        verbose_name="Importance",
                    ),
                ),
                (
                    "is_inquirer_emailed",
                    models.BooleanField(
                        default=False,
                        help_text="Is the inquirer emailed",
                        verbose_name="Is inquirer emailed",
                    ),
                ),
                (
                    "is_respondent_emailed",
                    models.BooleanField(
                        default=False,
                        help_text="Is the respondent emailed",
                        verbose_name="Is respondent emailed",
                    ),
                ),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        help_text="Custom data of the inquiry",
                        null=True,
                        verbose_name="Data",
                    ),
                ),
                (
                    "request_datasheet",
                    models.BooleanField(
                        default=False,
                        help_text="Request datasheet of the item",
                        verbose_name="Request datasheet",
                    ),
                ),
                (
                    "request_icd",
                    models.BooleanField(
                        default=False,
                        help_text="Request ICD of the item",
                        verbose_name="Request ICD",
                    ),
                ),
                (
                    "request_options_sheet",
                    models.BooleanField(
                        default=False,
                        help_text="Request options sheet of the item",
                        verbose_name="Request options sheet",
                    ),
                ),
                (
                    "request_user_manual",
                    models.BooleanField(
                        default=False,
                        help_text="Request user manual of the item",
                        verbose_name="Request user manual",
                    ),
                ),
                (
                    "request_cad_model",
                    models.BooleanField(
                        default=False,
                        help_text="Request CAD model of the item",
                        verbose_name="Request CAD model",
                    ),
                ),
                (
                    "request_quotation",
                    models.BooleanField(
                        default=False,
                        help_text="Request quotation of the item",
                        verbose_name="Request quotation",
                    ),
                ),
                (
                    "request_lead_time",
                    models.BooleanField(
                        default=False,
                        help_text="Request lead time of the item",
                        verbose_name="Request lead time",
                    ),
                ),
                (
                    "request_heritage",
                    models.BooleanField(
                        default=False,
                        help_text="Request heritage of the item",
                        verbose_name="Request heritage",
                    ),
                ),
                (
                    "number_of_flight_units",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of flight units of the item",
                        null=True,
                        verbose_name="Number of flight units",
                    ),
                ),
                (
                    "number_of_engineering_units",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of engineering units of the item",
                        null=True,
                        verbose_name="Number of engineering units",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Country of the person making the inquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_inquiries",
                        to="core.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted the item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "inquirer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Inquirer of the inquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_inquirer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inquirer",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item of the inquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_inquiries",
                        to="catalog.taxonomyitem",
                        verbose_name="Item",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified the item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supplier of the item inquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_inquiries",
                        to="supplier.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item inquiry",
                "verbose_name_plural": "Item inquiries",
                "ordering": ["date_created"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the item",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time when the item was created modified",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time when the item was last modified",
                        verbose_name="Date modified",
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        blank=True,
                        help_text="Server date and time when the item was deleted",
                        null=True,
                        verbose_name="Date deleted",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the item has been deleted or not",
                        verbose_name="Is deleted",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the inquirer",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the inquirer",
                        max_length=255,
                        verbose_name="Email",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization of the inquirer",
                        max_length=255,
                        null=True,
                        verbose_name="Organization",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Position of the person making the inquiry",
                        max_length=255,
                        null=True,
                        verbose_name="Position",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Message of the person making the inquiry",
                        max_length=6000,
                        verbose_name="Content",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes of the inquiry",
                        max_length=6000,
                        null=True,
                        verbose_name="Notes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("error", "Error"),
                            ("other", "Other"),
                        ],
                        default="processing",
                        help_text="Status of the inquiry",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "importance",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="unknown",
                        help_text="Importance of the inquiry",
                        max_length=20,
                        verbose_name="Importance",
                    ),
                ),
                (
                    "is_inquirer_emailed",
                    models.BooleanField(
                        default=False,
                        help_text="Is the inquirer emailed",
                        verbose_name="Is inquirer emailed",
                    ),
                ),
                (
                    "is_respondent_emailed",
                    models.BooleanField(
                        default=False,
                        help_text="Is the respondent emailed",
                        verbose_name="Is respondent emailed",
                    ),
                ),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        help_text="Custom data of the inquiry",
                        null=True,
                        verbose_name="Data",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Country of the person making the inquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_inquiries",
                        to="core.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted the item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Deleted by",
                    ),
                ),
                (
                    "inquirer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Inquirer of the inquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_inquirer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Inquirer",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last modified the item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified by",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supplier of the item inquiry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_inquiries",
                        to="supplier.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier inquiry",
                "verbose_name_plural": "Supplier inquiries",
                "ordering": ["date_created"],
            },
        ),
    ]
