# Generated by Django 5.0.4 on 2024-12-06 05:08

import apps.accounts.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Unique email address",
                        max_length=255,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Unique username associated with the account",
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_username",
                                message='Username must be alphanumeric or contain any of the following: "_"',
                                regex="^[a-zA-Z0-9_]*$",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=4,
                                message="Username must be at least 4 characters long",
                            ),
                        ],
                        verbose_name="Username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First name of the user",
                        max_length=120,
                        verbose_name="First name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Last name of the user",
                        max_length=120,
                        verbose_name="Last name",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="User bio",
                        max_length=1000,
                        verbose_name="Bio",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="User organization",
                        max_length=255,
                        null=True,
                        verbose_name="Organization",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="User position",
                        max_length=255,
                        null=True,
                        verbose_name="Position",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site",
                        verbose_name="Staff status",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site",
                        verbose_name="Admin status",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them",
                        verbose_name="Superuser status",
                    ),
                ),
                (
                    "profile_image_raw",
                    models.ImageField(
                        blank=True,
                        help_text="Raw profile image or avatar of the account",
                        null=True,
                        upload_to=apps.accounts.models.Account.profile_image_raw_upload_path,
                        verbose_name="Profile image raw",
                    ),
                ),
                (
                    "profile_image_raw_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the raw profile image or avatar of the account, using the MD5 hash algorithm",
                        max_length=255,
                        null=True,
                        verbose_name="Profile image raw hash",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text='Processed profile image in WEBP format.                                                <br>Required image size: 640x640                                                <br>Required image aspect ratio: 1.0                                                <br>The profile image should be uploaded to the "profile_image_raw" field and the model will                                                process the profile image and generate the "profile_image" and "profile_image_thumbnail" image and                                                set the value for the fields.',
                        null=True,
                        upload_to=apps.accounts.models.Account.profile_image_processed_upload_path,
                        verbose_name="Profile image",
                    ),
                ),
                (
                    "profile_image_thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text='Processed profile image thumbnail in WEBP format.                                                <br>Required image size: 640x640                                                <br>Required image aspect ratio: 1.0                                                <br>The profile image should be uploaded to the "profile_image_raw" field and the model will                                                process the profile image and generate the "profile_image" and "profile_image_thumbnail" image and                                                set the value for the fields.',
                        null=True,
                        upload_to=apps.accounts.models.Account.profile_image_thumbnail_processed_upload_path,
                        verbose_name="Profile image thumbnail",
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has verified their email address",
                        verbose_name="Is email verified",
                    ),
                ),
                (
                    "email_verification_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for the email verification token",
                        unique=True,
                        verbose_name="Email verification token",
                    ),
                ),
                (
                    "email_verification_token_expiration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Server date and time when the email verification token expires",
                        null=True,
                        verbose_name="Email verification token expiration date",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has marked their account for                                                 deletion",
                        verbose_name="Is marked for deletion",
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        blank=True,
                        help_text="Server date and time when the user deleted their                                                    account",
                        null=True,
                        verbose_name="Date marked for deletion",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the account",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "short_uuid",
                    models.CharField(
                        editable=False,
                        help_text="Short unique identifier for the account",
                        max_length=12,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=12,
                                message="Short UUID must be exactly 12 characters long",
                            )
                        ],
                        verbose_name="Short UUID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time the account was created",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_last_logged_in",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time the account last logged in",
                        verbose_name="Date last logged in",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Country of the user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="AccountInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the account settings",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time when the item was created modified",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time when the item was last modified",
                        verbose_name="Date modified",
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        help_text="Account that is connected to the settings",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account",
                    ),
                ),
                (
                    "followers",
                    models.ManyToManyField(
                        help_text="Accounts that are following this account",
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Followers",
                    ),
                ),
                (
                    "following",
                    models.ManyToManyField(
                        help_text="Accounts that this account is following",
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Following",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account interaction",
                "verbose_name_plural": "Account interactions",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="AccountSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("system", "System"),
                        ],
                        default="system",
                        help_text="User website theme",
                        max_length=55,
                        verbose_name="Theme",
                    ),
                ),
                (
                    "is_profile_public",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether the user profile can be viewed by others",
                        verbose_name="Profile public",
                    ),
                ),
                (
                    "show_email",
                    models.BooleanField(
                        default=False,
                        help_text="Show or hide the email",
                        verbose_name="Show email",
                    ),
                ),
                (
                    "receive_marketing_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Receive marketing emails",
                        verbose_name="Marketing emails",
                    ),
                ),
                (
                    "receive_weekly_digest_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Receive weekly digest emails",
                        verbose_name="Weekly digest emails",
                    ),
                ),
                (
                    "receive_discovery_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Receive emails about new features and tips",
                        verbose_name="Discovery emails",
                    ),
                ),
                (
                    "receive_site_update_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Receive site update emails",
                        verbose_name="Site updates",
                    ),
                ),
                (
                    "receive_inbox_message_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications when you receive a new                                                              message in your inbox",
                        verbose_name="Inbox message notifications",
                    ),
                ),
                (
                    "receive_announcement_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications about new announcements",
                        verbose_name="Announcement notifications",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the account settings",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Server date and time when the item was created modified",
                        verbose_name="Date created",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Server date and time when the item was last modified",
                        verbose_name="Date modified",
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        help_text="Account that is connected to the settings",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account setting",
                "verbose_name_plural": "Account settings",
                "ordering": ["-date_created"],
            },
        ),
    ]
